discovery:
  instrument:
    - k8s_deployment_name: frontend
    - k8s_deployment_name: name-generator
attributes:
  kubernetes:
    enable: true
prometheus_export:
  port: 9999
  features:
    - application
    - application_span
    - application_service_graph
    - application_process
    - network
    - application_host
    - network_inter_zone
otel_traces_export:
  endpoint: http://tempo:4318
ebpf:
  context_propagation: all
