{
 "title": "Latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "What the frontend sees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{job=\"default/frontend\", span_kind=\"SPAN_KIND_CLIENT\"}[5m])) by (le, span_name))",
     "legendFormat": "95% latency for {{span_name}}"
    }
   ]
  },
  {
   "title": "Beyla",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{job=\"default/name-generator\", span_kind=\"SPAN_KIND_SERVER\"}[5m])) by (le, span_name, source))",
     "legendFormat": "95% latency for {{span_name}}"
    }
   ]
  },
  {
   "title": "OpenTelemetry Java Instrumentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=~\".*name-generator.*\"}[5m])) by (le, http_route))",
     "legendFormat": "95% latency for {{http_route}}"
    }
   ]
  }
 ]
}