{
 "title": "RED metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": {
     "query": "label_values(traces_spanmetrics_latency,service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${service_name}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service_name" },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (histogram_count(rate(traces_spanmetrics_latency{service_name=~\"${service_name}\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "requests/second"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(histogram_count(rate(traces_spanmetrics_latency{service_name=~\"${service_name}\", span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval]))) OR on() vector(0)) / sum(histogram_count(rate(traces_spanmetrics_latency{service_name=~\"${service_name}\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "percentage of HTTP 5xx status codes"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(traces_spanmetrics_latency{service_name=~\"${service_name}\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(traces_spanmetrics_latency{service_name=~\"${service_name}\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum by (le) (rate(traces_spanmetrics_latency{service_name=~\"${service_name}\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "98th percentile"
    }
   ]
  }
 ]
}