apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-generator
  labels:
    app: name-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-generator
  template:
    metadata:
      labels:
        app: name-generator
    spec:
      containers:
      - name: name-generator
        image: voxxed-days-crete/name-generator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: name-generator
spec:
  selector:
    app: name-generator
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
